### ISSUE TITLE
Brand/Identity

### ISSUE THREAD

**Issue by misscs** [GothamSass/chrysler#10]
- [x] Upload other sass meetup logos for inspiration
- [x] Upload current sketches/concepts 
- [x] Create a temporary logo

**Comment by adekunleoduye** [comment]
@misscs @nonlinear:
The link below are some logo concepts I had, I know we're going with the dribbble logo but here are some other opinions we might want to consider.

https://www.dropbox.com/s/9spgtzbv8fb8y2y/gotham-sass_draft__2.pdf?dl=0

**Comment by misscs** [comment]
I think this issue is resolved, right? 

We do need to talk to whomever designed the Dribbble logo still #59
