### ISSUE TITLE
Event Section

### ISSUE THREAD

**Issue by misscs** [GothamSass/chrysler#46]
Event section will list current and past events. We'll determine upcoming and past by event date. 

* Event title
* Speakers
  * Name
  * Social
  * Photo
  * Topic

- [x] @rabellamy Create markup for the event teaser
- [ ] Event (node) page)
- [x] @nonlinear Style event component
- [x] @misscs Populate event JSON file (ideally export from meetup) #3 
- [ ] Style archive/past events

**Comment by misscs** [comment]
I'd love to leverage microformats hevent for event markup if only for the fact that we can easily generate `.ics` files for users to add our events to their calendars. Thoughts?

**Comment by rabellamy** [comment]
Sounds like a good idea to explore....

**Comment by misscs** [comment]
Here's an example response from Meetup. Our event object won't have all of the fields nor will we store some of timestamp info the same way, but it is helpful so we can mimic what's there. We'll have different fields. In the end, Meetup is just for past data for our archive. Which means we can have two json files, one for us moving forward and one for all past events. 

```json
{
"status": "upcoming",
"visibility": "public",
"maybe_rsvp_count": 0,
"venue": {
"id": 15942472,
"zip": "10011",
"lon": -73.994774,
"repinned": false,
"name": "Pivotal Labs",
"state": "NY",
"address_1": "625 Avenue of Americas, 2nd Floor",
"lat": 40.74021,
"city": "New York",
"country": "us"
},
"id": "dzqhblytcbbc",
"utc_offset": -18000000,
"duration": 10800000,
"time": 1421798400000,
"waitlist_count": 0,
"announced": true,
"updated": 1417036401000,
"yes_rsvp_count": 22,
"created": 1414986101000,
"event_url": "http://www.meetup.com/gothamsass/events/218778325/",
"description": "<p>Have questions that need answers? Have some knowledge you would like to share?</p> <p>Come out and hack with us!</p> <p>Big thanks to our host :</p> <p><br/><img src="http://photos4.meetupstatic.com/photos/event/a/b/7/e/600_429283902.jpeg" /></p>",
"name": "SassHack: Bring questions, your projects, your knowledge.",
"headcount": 0,
"group": {
"id": 3610272,
"created": 1333597165000,
"group_lat": 40.720001220703125,
"name": "New York Sass & Compass Meetup",
"group_lon": -73.98999786376953,
"join_mode": "open",
"urlname": "gothamsass",
"who": "Sasstronauts"
}
}
```

**Comment by misscs** [comment]
Proposal for event object architecture. Standardizes keys for Meetup.com data. Let me know what you think. 

```json
{
  "name": "The Current State of Sass",
  "description":"Chris Eppstein, creator of Compass, talks about what's to come in Sass 3.3, and Alan Hogan on simplifying responsive web design with Sass",
  "date": "2012-04-23T18:25:43.511Z",
  "venue": {
    "name": "Pivotal Labs",
    "address_1": "625 Avenue of Americas, 2nd Floor",
    "address_2": null,
    "city": "New York"
  },
  "sponsors": [
    {
      "name": "Pivotal Labs",
      "description": "Short description about sponsor",
      "logo": null,
      "url": "http://pivotal.com",
      "social": {
        "twitter": "pivotalnyc",
        "hash": "#pivotalrocks"
      }
    }
  ],
  "speakers": [
    {
      "name": "Chris Eppstein",
      "photo": {
        "path": null,
        "alt": null
      },
      "bio": "I'm the creator of [compass-style](compass-style.org)Compass, a stylesheet authoring framework and I'm on the core team of Sass — the stylesheet syntax upon which Compass is built. I maintain about a dozen less well known ruby libraries and rails plugins on github, and am an active contributor of patches to the many open source projects that I use.",
      "social": {
        "twitter": "chriseppstein",
        "github": "chriseppstein"
      },
      "title": "title of the speaker's presentation",
      "description": "this is a longer description for a speaker's topic if we have multiple speakers"
    },
    {
      "speaker_name": "Chris Eppstein 2",
      "photo": {
        "path": null,
        "alt": null
      },
      "bio": "I'm the creator of [compass-style](compass-style.org)Compass, a stylesheet authoring framework and I'm on the core team of Sass — the stylesheet syntax upon which Compass is built. I maintain about a dozen less well known ruby libraries and rails plugins on github, and am an active contributor of patches to the many open source projects that I use.",
      "social": null,
      "title": null,
      "description": null
    }
  ]
}
```

Thoughts

* let users submit bios as markdown so they can include links. harp has a markdown filter we can use on the field
* speaker topic and description can be `null` if they are the same as the main event title and description
* down the line we can do something nicer with location data. it would be nice to have a map and even nicer if we could easily reference location from a shared file (pipe dreams)

**Comment by misscs** [comment]
Only field i'm not too certain of is `date`. I like how @rabellamy sample data includes the time and date in one, but i wonder if we should separate the `date` and `time` for clarity. definitely don't want to copy how meetup handles it. there's is fancy for dealing with the complexities of a global system. 

```
"utc_offset": -18000000,
"duration": 10800000,
"time": 1421798400000,
```

**Comment by rabellamy** [comment]
Nice, I will incorporate the proposal and update the PR.

**Comment by misscs** [comment]
Added another task for display of the archive section. We may end up splitting out the styling of this story into two issues to not hold up merge

**Comment by misscs** [comment]
@rabellamy can you let us know where you are with events? just leave a comment on this ticket. thanks!

**Comment by rabellamy** [comment]
@misscs, @nonlinear, @skyfaerie, @rmjames and @adekunleoduye 
  
What I have done:
* I created an example event _data.json
* I created the initial markup for event teaser and an event page

What I am planning on doing:
* refining all markup

What I need feedback on:
* the event JSON 
* all markup
* what date format we are going to use

Thanks!!

**Comment by misscs** [comment]
@rabellamy i believe we've addressed everything for events functionally. probably some style clean-up but no reason to keep this ticket open. If there isn't a sep ticket for archive/past events section, can you create one to capture that task? Otherwise this is done.
