### ISSUE TITLE
Why the Designer Failed FizzBuzz: Identity Crisis on the Front-end

### ISSUE THREAD

**Issue by laras126** [GothamSass/chrysler#92]
#### Summary:
* Standard length (20-30mins + discussion)
* Level/Audience: Everyone

I’m one of those hybrid designer/developers. Unicorn? No. I failed FizzBuzz in an interview as a result of a self-taught skill-set and an ambiguous job posting. Does that mean I’m not a “real” developer? To some yes, to others no. Then what do I call myself? Am I a liar, a fake? Whatever the case, I’m not alone here.

This isn’t the impostor syndrome. It’s the result of an industry in its awkward twenties; it’s identity crisis and it’s ego. We aren’t fakes, we just don’t know how to accurately communicate our skills. In this talk, I’ll start by reviewing the heated responses to [an article I wrote](https://css-tricks.com/tales-of-a-non-unicorn-a-story-about-the-trouble-with-job-titles-and-descriptions/) about the above scenario. Then I’ll propose a four part lexicon for job titles and descriptions in the web industry; a vocabulary that both standardizes our roles, yet allows for the rapidly changing nature of what we do. Whether or not my lexicon is the one that works, let’s start talking about it.

#### Takeaways:

- A call to be more conscious of terminology in job postings, and suggestions for simple changes to descriptions.
- Evaluating candidates’ qualifications: getting away from the idea of a “checklist”, focusing more on a capacity to learn, passion for the craft, and community participation.
- A system of terms and definitions (lexicon) for job postings where all job titles follow a three part structure:
	1. Junior, Mid-level, or Senior
	2. Skill-set (e.g. backend, frontend, UX, etc.)
	3. Generalist or Specialist
- Start a conversation around the standardization of job titles and descriptions.
- Propose a structured way to format job postings.

#### Me:

* Name: Lara Schenck
* Gender: She
* Role: Independent Teacher/Consultant 
* Twitter: [@laras126](http://twitter.com/laras126)
* Website: [notlaura.com](http://notlaura.com)
* Headshot: https://www.dropbox.com/s/xucqbraswja2klz/lara-pic.png?dl=0

Lara Schenck is an independent web consultant and teacher in New York City. She teaches front-end development to designers at Pratt Institute, facilitates corporate trainings with [Decoded](http://decoded.com), and organizes private classes and workshops. Lara is a dedicated cocktail enthusiast and grew up on a llama farm outside of Pittsburgh (true story).

**Comment by adekunleoduye** [comment]
@laras126 Thanks for being the bravest one and submitting a talk! If it isn't too much to ask, can you move this talk submission to the Central Park repo (https://github.com/GothamSass/centralpark/issues)?

Thanks in advance!

**Comment by laras126** [comment]
You got it!
